### ISSUE TITLE
RunGrepTest issue on OpenBSD

### ISSUE THREAD

**Issue by PhilipHazel** [PhilipHazel/pcre2#10]
This is #2680 in the old Bugzilla, submitted by Nam Nguyen.

RunGrepTest fails on Test 132 for me on OpenBSD.

```
./testdata/grepoutput expects an 'a' at the end.
---------------------------- Test 132 -----------------------------
match 1:
 a
match 2:
 b
---
 a
RC=0

```
I actually get no 'a' when I run RunGrepTest:
```
---------------------------- Test 132 -----------------------------
match 1:
 a
match 2:
 b
---
RC=0

```
Manually running this test I can't see how it produces 'a' after the '---':
```
$ (pcre2grep -m1 -A3 '^match'; echo '---'; head -1) < testdata/grepinput
match 1:
 a
match 2:
 b
---
```

PH: The idea of this test is to check that the standard input is left in the right place when pcre2grep stops because it has reached the -m limit. The "a" line is generated by the "head -1" command when run under Linux (which is all I have):

```
$ (./pcre2grep -m1 -A3 '^match'; echo '---'; head -1) < testdata/grepinput
match 1:
 a
match 2:
 b
---
 a
```

Looks like this is yet another Linux/BSD difference. Sigh. I think the relevant code is around line 2589 in pcre2test.c:

```
  /* If the -m option set a limit for the number of matched or non-matched
  lines, check it here. A limit of zero means that no matching is ever done.
  For stdin from a file, set the file position. */                         
                                                                            
  if (count_limit >= 0 && count_matched_lines >= count_limit)             
    {                                                                   
    if (frtype == FR_PLAIN && filename == stdin_name && !is_file_tty(handle))
      (void)fseek(handle, (long int)filepos, SEEK_SET);             
    rc = (count_limit == 0)? 1 : 0;                                     
    break;                                                             
    }
```

**Comment by carenas** [comment]
FWIW, it also fails in Minix, NetBSD, FreeBSD and AIX (might fail also in other *NIX, but I don't have access to them to check).

Solaris also fails if using the default /bin/sh but succeeds if using bash, but somehow it works in Windows, macOS and Linux.

The underlying code is not compatible with ANSI C 17[1] which specifies in 7.21.9.2.4:

"For a text stream, either offset shall be zero, or offset shall be a value returned by an earlier
successful call to the ftell function on a stream associated with the same file and whence shall be
SEEK_SET."

It seems though the problematic code from BSD or their interpretation on how to handle stdin might get in the way anyway, and so I think it is better (and likely equally portable) to use lseek instead, which I prototyped/tested already in [carenas/pcre2@c48a6ed63473bfdc78f813723e5aa20a7c983b71]

[1] https://web.archive.org/web/20181230041359/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf

**Comment by noloader** [comment]
@carenas,

My apologies for digging into an old issue... You might consider adding Alpine Linux to your test lab. Alpine uses Musl, and Musl has sharp edges like this.

**Comment by PhilipHazel** [comment]
Test Lab? That would be a luxury. I'm afraid all I have access to is my Arch Linux box and one or two accounts on other systems.

**Comment by ltrzesniewski** [comment]
@PhilipHazel maybe it's the right time to consider #19 🙂 

I made the CI super simple to begin with, but it could be extended to run tests in an Alpine contanier.

**Comment by PhilipHazel** [comment]
Ah, maybe I should find some time to research what can be done that way.
Thank you for the prod.

Regards,
Philip
