### ISSUE TITLE
Duplicate names and callouts

### ISSUE THREAD

**Issue by 6a4h8** [PhilipHazel/pcre2#17]
I have a function that is searching for the nearest named group by name by measuring the distance from the nametable and last capture_last callout structure field.

It seems to be buggy.

Like how do I get the most recent (actually only one normally in the current subroutine) named group when duplicate names are allowed?

**Comment by PhilipHazel** [comment]
Duplicate names are most useful in patterns when only one of the duplicates can be set in any given match, for example, if each one is in a separate branch. If more than one is set, there is no direct way to tell which was most recent. I think the only way you could achieve this would be to make use of different (*MARK) items.

**Comment by 6a4h8** [comment]
@PhilipHazel  Thanks for the tip - how exactly would I achieve that?

**Comment by PhilipHazel** [comment]
Read the documentation about the pcre2_get_mark() function. I'm going to close this issue now.
