### ISSUE TITLE
pcre2.h missing on CentOS 7, even after installing pcre2

### ISSUE THREAD

**Issue by iGovindY** [PhilipHazel/pcre2#20]
Hi,

I am not sure if this is the right place to raise this issue.
On CentOS 7, when we install pcre2 with the below command.
`yum install pcre2`

It doesn't; install `pcre2.h` file along with other files like `.so`.
Am I doing something wrong? or its a bug in CentOS packaging?

Also, I tried installing using `rpm`, same issue no luck.
https://centos.pkgs.org/7/centos-x86_64/pcre2-10.23-2.el7.x86_64.rpm.html
As this page shows under **Files** header it also doesn't install pcre2.h file.

Thanks in advance for help.

**Comment by PhilipHazel** [comment]
The normal default place for pcre2.h is /usr/linclude or /usr/local/include. Have you tried looking for it with "find" or "locate". In any event, this is a CentOS issue, not a PCRE2 one.

**Comment by iGovindY** [comment]
wanted to update here, if anyone faces similar issue.

looks like for build environment `pcre2-devel` package should be installed, which installs headers also.
for run time environment `pcre2` package is enough.

So, `yum install pcre2-devel` should solve the above issue.
