### ISSUE TITLE
ftp.pcre.org is not accessable !

### ISSUE THREAD

**Issue by elkadrey** [PhilipHazel/pcre2#38]
Hi
https://ftp.pcre.org/ is always timeout and my server cannot complete the installation (CWP7)

Please help

**Comment by PhilipHazel** [comment]
ftp.pcre.org was the old site for PCRE1 and PCRE2 distribution. PCRE1 (the 8.xx series) is now at end-of-life and is no longer maintained. The final release is 8.45. PCRE2 development has moved to GitHub and you can get the latest 10.xx releases here.
