### ISSUE TITLE
Could not reach ftp.pcre.org 

### ISSUE THREAD

**Issue by vinhnguyen-ubitec** [PhilipHazel/pcre2#44]
I tried to install some lua modules for OpenResty, in the installation process, it download something from ftp.pcre.org, and the connection could not be established.

I tried many time, and the error is:

```
#5 594.7 curl: (7) Failed to connect to ftp.pcre.org port 443 after 76416 ms: Connection refused
```

Please see more detail in <https://github.com/openresty/docker-openresty/issues/193>
The fix in OpenResty: <https://github.com/openresty/docker-openresty/commit/a3a1a3a27a3d9c93f917ef450b7ab4b183698f5a>

**Comment by MatthewVernon** [comment]
That's an issue with OpenResty - it should be downloading PCRE from github now.

**Comment by vinhnguyen-ubitec** [comment]
Thank @MatthewVernon, I checked on OpenResty, they changed to download from SourceForge now.
