### ISSUE TITLE
pcre2 causes crash with alignment issue (Bus Error) in exim on SPARC

### ISSUE THREAD

**Issue by glaubitz** [PhilipHazel/pcre2#59]
The `exim` mailer daemon switched to `pcre2` in version 4.95. Ever since, the `exim` daemon crashes with a `Bus Error` on SPARC on Linux:

```
glaubitz@gcc202:~/exim$ ./src/build-Linux-sparc64/exim
Bus error
glaubitz@gcc202:~/exim$
```

Bisecting the issue lead to the change which switched `exim` from `pcre` to `pcre2` (https://github.com/Exim/exim/commit/22ed7a5295f196fce32563f6e9c669110dd36f4d).

Running the `exim` binary in `gdb`, lead to the following backtrace:

```
(gdb) bt
#0  pcre2_general_context_create_8 (private_malloc=0x1000004f680 <function_store_malloc>, 
    private_free=0x1000004f650 <function_store_free>, memory_data=0x0) at src/pcre2_context.c:123
#1  0x00000100000517a8 in main ()
(gdb)
```

Access to a SPARC machine running Linux or Solaris can be obtained through the GCC Compile Farm, see: https://gcc.gnu.org/wiki/CompileFarm

**Comment by PhilipHazel** [comment]
Have you reported this to the Exim people? It seems unlikely to be a PCRE2 issue.

**Comment by glaubitz** [comment]
Yes, reported as https://bugs.exim.org/show_bug.cgi?id=2838.

I'm actually not sure yet whether the problem is in `pcre2` or `exim`, I'm still debugging.

Sorry if this has caused unnecessary noise.

**Comment by glaubitz** [comment]
OK, I have identified the issue as a bug in exim and not pcre. Thus, closing this issue.
