### ISSUE TITLE
FTP/HTTP/Conan not working?

### ISSUE THREAD

**Issue by hanusek** [PhilipHazel/pcre2#60]
Hello.
I have a problem with download from conan-center.
```
pcre/8.45: Configuring sources in /root/.conan/data/pcre/8.45/_/_/source
ERROR: Error downloading file https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre-8.45.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2dd13fa640>, 'Connection to ftp.pcre.org timed out. (connect timeout=60.0)'))'
```
Target: https://ftp.pcre.org/pub/pcre

**Comment by PhilipHazel** [comment]
PCRE 8.45 is obsolete and no longer maintained. PCRE2 (the 10.xx series) has been around for 7 years now. Recently, the old FTP site has closed down, and PCRE2 has now moved to GitHub, as announced on pcre-dev some time ago. I believe you can still get a tarball for the obsolete 8.45 from SourceForge.
