### ISSUE TITLE
[Conan] Building on Windows 10 x86 - linking error

### ISSUE THREAD

**Issue by hanusek** [PhilipHazel/pcre2#61]
Hello!
I am trying compile on Windows by conan.

**Library:** [pcre/8.45](https://conan.io/center/pcre?tab=overview&os=Windows)
**Operating System:** Windows 10 (x86)
**Compiler version:** VS 15
**Conan version:** conan 1.43.0
**Python version:** Python 3.8.0

**Conan profile:**
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86
compiler=Visual Studio
compiler.version=15
build_type=Debug
```

**Error:** [Full log](https://gist.github.com/hanusek/ea28484bccb39213c640e36fc2b28e27)
```
pcregrep.obj : error LNK2019: nierozpoznany zewnŕtrzny symbol _BZ2_bzopen@8 przywo│any w funkcji _grep_or_recurse [C:\Users\mhanu\.conan\data\pcre\8
.45\_\_\build\752948ce548bd345ffbb13d47bc67547d791cc18\build_subfolder\source_subfolder\pcregrep.vcxproj]
pcregrep.obj : error LNK2019: nierozpoznany zewnŕtrzny symbol _BZ2_bzread@12 przywo│any w funkcji _pcregrep [C:\Users\mhanu\.conan\data\pcre\8.45\_\
_\build\752948ce548bd345ffbb13d47bc67547d791cc18\build_subfolder\source_subfolder\pcregrep.vcxproj]
pcregrep.obj : error LNK2019: nierozpoznany zewnŕtrzny symbol _BZ2_bzclose@4 przywo│any w funkcji _grep_or_recurse [C:\Users\mhanu\.conan\data\pcre\
8.45\_\_\build\752948ce548bd345ffbb13d47bc67547d791cc18\build_subfolder\source_subfolder\pcregrep.vcxproj]
pcregrep.obj : error LNK2019: nierozpoznany zewnŕtrzny symbol _BZ2_bzerror@8 przywo│any w funkcji _grep_or_recurse [C:\Users\mhanu\.conan\data\pcre\
8.45\_\_\build\752948ce548bd345ffbb13d47bc67547d791cc18\build_subfolder\source_subfolder\pcregrep.vcxproj]
C:\Users\mhanu\.conan\data\pcre\8.45\_\_\build\752948ce548bd345ffbb13d47bc67547d791cc18\build_subfolder\bin\pcregrep.exe : fatal error LNK1120: licz
ba nierozpoznanych elementˇw zewnŕtrznych: 4 [C:\Users\mhanu\.conan\data\pcre\8.45\_\_\build\752948ce548bd345ffbb13d47bc67547d791cc18\build_subfolde
r\source_subfolder\pcregrep.vcxproj]
pcre/8.45:
pcre/8.45: ERROR: Package '752948ce548bd345ffbb13d47bc67547d791cc18' build failed
```

**Comment by PhilipHazel** [comment]
You are in the wrong place. This GitHub project is for PCRE2 (the 10.xx series). The 8.xx series is PCRE1, which is obsolete and no longer maintained. In any case, this looks more like some kind of packaging issue rather than a PCRE issue. It does look as if it's compiled the library, but failed on the pcregrep program.

**Comment by hanusek** [comment]
> You are in the wrong place. This GitHub project is for PCRE2 (the 10.xx series). The 8.xx series is PCRE1, which is obsolete and no longer maintained. In any case, this looks more like some kind of packaging issue rather than a PCRE issue. It does look as if it's compiled the library, but failed on the pcregrep program.

Ok but... I have the same problem with **PCRE2**.
https://github.com/conan-io/conan-center-index/issues/8382

**Comment by PhilipHazel** [comment]
You will need to find somebody who understands Windows and Microsoft VS and conan; I am not a Windows user, and I've never heard of conan, so I don't know what it does. PCRE2 is provided with two building methods: Autotools (./configure) or CMake. If there is an issue with one of them, we can try to fix it, The errors you posted above are not in English, but my guess is that it is trying to link pcre2grep and not finding the PCRE2 library. I still think this is some kind of packaging issue.
