### ISSUE TITLE
RunTests.bat on Windows fails test 8 for me

### ISSUE THREAD

**Issue by eli-schwartz** [PhilipHazel/pcre2#65]
I don't know what the cause of this might be. I have a thirdparty port of pcre2 to the Meson build system (for embedding into other projects using meson) and as part of the port we try to run the testsuite.

For reference, here is the meson build description: https://github.com/mesonbuild/wrapdb/blob/pcre2/subprojects/packagefiles/pcre2/meson.build

In our Github CI, everything works fine on Ubuntu. On Windows using MSVC, I get this error instead:

https://github.com/mesonbuild/wrapdb/runs/4637121959?check_suite_focus=true#step:6:261

```
Test 8: "Internal offsets and code size tests"

          failed comparison: fc /n D:\a\wrapdb\wrapdb\subprojects\pcre2-10.39\testdata\testoutput8-8-2 testout8\testoutput8-8-2
```

Do you have any idea what the problem might be? Suggestions for figuring out the problem?

Is this an expected failure? There isn't currently any publicly visible CI for pcre2 (and an open PR only adds some for linux) so it is difficult to know for sure...

**Comment by PhilipHazel** [comment]
Nobody else has reported problems with Windows, but they may just have ignored this one. I am not a Windows user, and someone else wrote RunTest.bat. Can you post the difference(s) between the two files?

**Comment by eli-schwartz** [comment]
After some fiddling around with github I was able to get it to upload the second file.
[testoutput8-8-2.txt](https://github.com/PhilipHazel/pcre2/files/7798553/testoutput8-8-2.txt)

Looks like about 200 lines at the end simply don't exist. :/

**Comment by eli-schwartz** [comment]
https://github.com/lite-xl/lite-xl/pull/785#discussion_r777247784

@Jan200101 debugged this and noticed that it reports

> Failed: error 184 at offset 1504: (?| and/or (?J: or (?x: parentheses are too deeply nested

**Comment by PhilipHazel** [comment]
That is not an issue. It is testing that it is detecting that situation (see the output in testoutput-8-8-2). Can this issue now be closed?

**Comment by Jan200101** [comment]
Yes thats expected, the issue is that stops in the middle of the test (at https://github.com/PhilipHazel/pcre2/blob/31fb2e58a19cfdf5809ff952025b7f4329480337/testdata/testoutput8-8-2#L850 to be exact)

I managed to replicate this on a fresh Windows 10 machine running Visual Studio Community 2022.

Increasing `LINK_SIZE` from 2 to 4 caused the test to pass successfully

**Comment by Jan200101** [comment]
Further investigation shows that this was complete nonsense, the issue lies on the wrapdb side.
https://github.com/PhilipHazel/pcre2/blob/31fb2e58a19cfdf5809ff952025b7f4329480337/CMakeLists.txt#L869
This flag is what is missing in the meson.build

**Comment by PhilipHazel** [comment]
Glad to hear this is resolved. This is not the first time that the small default size of the stack in Windows has been an issue. Sigh. Can this issue now be closed?

**Comment by Jan200101** [comment]
I believe so
