### ISSUE TITLE
yocto dunfell warning 

### ISSUE THREAD

**Issue by amamory** [PhilipHazel/pcre2#75]
yocto dunfell, a LTS version of yocto, is complaining about a missing release:

```
WARNING: libpcre2-native-10.34-r0 do_fetch: Failed to fetch URL https://github.com/PhilipHazel/pcre2/releases/download/pcre2-10.34/pcre2-10.34.tar.bz2, attempting MIRRORS if available
```
I noted that this release has been removed from github.

**Comment by PhilipHazel** [comment]
10.34 predates the move to GitHub and was never available from GitHub. It was released in November 2019, so is quite old now. You might be able to find a copy on Sourceforge.

**Comment by amamory** [comment]
understood ! so it seems that yocto guys have to update it from their side.
thanks!
