### ISSUE TITLE
github release pgp key?

### ISSUE THREAD

**Issue by piratejon** [PhilipHazel/pcre2#80]
Previously when I installed PCRE from ftp.pcre.org I would verify the signature with https://ftp.pcre.org/pub/pcre/Public-Key . Now I am migrating to PCRE2 -- where can I find the key to verify the signature for the PCRE2 github releases?

**Comment by PhilipHazel** [comment]
My public key is available from various keyservers. I have also uploaded it to GitHub via "Settings" under my profile. Not sure exactly how this appears to someone other than me looking at the project.

**Comment by piratejon** [comment]
Thank you. I found the one from Exim: https://ftp.exim.org/pub/exim/Public-Key . I also learned I can just --recv-keys 45F68D54BBE23FB3039B46E59766E084FB0F43D8.

**Comment by stevecj** [comment]
It would be nice if there was something at least a little more official than this. I can't see the key in the profile for @PhilipHazel, and I don't know an email with which to look it up on a key server. I can look up 45F68D54BBE23FB3039B46E59766E084FB0F43D8, but then I have to just assume that's the correct signature to import. I guess I can use @piratejon 's message above and the fact that nobody has said that's wrong as sort of a confirmation that it's right?

**Comment by NWilson** [comment]
The PGP keys are listed in the SECURITY.md file, which is on our website and also checked in to the repository:

* https://github.com/PCRE2Project/pcre2?tab=security-ov-file
* https://pcre2project.github.io/pcre2/project/security/
