### ISSUE TITLE
strange behaviour in matching (bug?)

### ISSUE THREAD

**Issue by ChristianS99** [PhilipHazel/pcre2#84]
```
echo -n 'rr' |rg -P '[Rr]{2}' -q; echo $?
1
```
```
echo -n 'rr' |rg -P '[rR]{2}' -q; echo $?
0
```
```
echo -n 'rr' |grep -P '[Rr]{2}' -q; echo $?
0
```
```
echo -n 'rr' |grep -P '[rR]{2}' -q; echo $?
0
```

rg is https://github.com/BurntSushi/ripgrep
ripgrep is using libpcre2, grep is using libpcre

same is visible in php7.4 and php8.1:
```
php > echo preg_match('/[rR]{2}/', 'rr');
1
php > echo preg_match('/[Rr]{2}/', 'rr');
0
```
that version also use libpcre2, php <=7.2 should use libpcre, but I don't have it available to test,
but you can try it on regex101.com and switch the flavours.

https://regex101.com/r/8Sfund/1
it has pcre2 preselected, that doesn't match and pcre matches, including all other flavours available there.

I'm no regex expert, let alone know about subtle differences between flavours, but for me it doesn't make sense, that the order of characters in [] matters, so I think it is a bug.
If not, please enlighten me, why this is, as it should be.

**Comment by PhilipHazel** [comment]
Thanks for the report, but this bug was recently reported and has already been fixed:

commit fdd94791086e466835ed61640cf31380efd1fbc5
Author: Philip Hazel <Philip.Hazel@gmail.com>
Date:   Wed Jan 26 08:37:18 2022 +0000

    Fix incorrect compiling when [Aa] etc. are quantified

**Comment by ChristianS99** [comment]
ok, sorry, only checked open issues, not closed ones

Fix is working for me, thx
