### ISSUE TITLE
Apologize, but no idea to where to ask, so asking here..

### ISSUE THREAD

**Issue by abdulbadii** [PhilipHazel/pcre2#88]
So apologize but really no idea to where to ask, so asking:
Is it supports the pattern-capturing group that is the one will capture/group a (sub) patterned group inside the whole regex pattern to be reused in next somewhere else in there?

If yes, would that perform the recursive regex and what version number exactly already has this feature ?

Thanks in advance

**Comment by PhilipHazel** [comment]
pcre2-dev@googlegroups.com might be a better place to ask this kind of question. PCRE2 (and PCRE1 before it) has always supported capturing groups, and recursive "subroutine" calls within patterns have been available for a very long time. There are lots of web sites with information about regex, for example regex101.com.
