### ISSUE TITLE
Missing fix.

### ISSUE THREAD

**Issue by osubboo** [PhilipHazel/pcre2#89]
I've previously filed a ticket that was merged/resolved:
https://bugs.exim.org/show_bug.cgi?id=2787

Nonetheless, checking the code for the latest 10.39 release and master, I do not see the fix:

https://github.com/PhilipHazel/pcre2/blob/master/src/sljit/sljitConfigInternal.h#L151

**Comment by PhilipHazel** [comment]
A large update to the JIT compiler has just been merged into master. Does that fix your issue?

**Comment by osubboo** [comment]
Yes, it does. Thanks.
