### ISSUE TITLE
excess element in struct initializer since recent ucd bitset change

### ISSUE THREAD

**Issue by saurik** [PhilipHazel/pcre2#90]
In #81 a field was removed from `ucd_record`, but in pcre2_ucd.c that means one of the 0's needs to be removed from the initializer.

https://github.com/PhilipHazel/pcre2/commit/e21345de97bad9236f9e246717d86b0c81b6cd75#diff-e3bd3003bdb0db9e9e2062bcfeb21b98399376a7d3b3a88460a0266e2df0df9aL1826-R1826

https://github.com/PhilipHazel/pcre2/blob/dea56d2df94546c23021a42d9395f2333589f01e/src/pcre2_ucd.c#L71

```
pcre2/src/pcre2_ucd.c:71:56: error: excess elements in struct initializer [-Werror,-Wexcess-initializers]
const ucd_record PRIV(ucd_records)[] = {{0,0,0,0,0,0,0,0 }};
                                                       ^
```

**Comment by PhilipHazel** [comment]
Thanks. This oversight would probably have been picked up when the full set of tests is run before a release, but it is as well to get it sorted early. I've committed the patch.
