### ISSUE TITLE
No ./configure in GitHub .Should I run autoconf ?

### ISSUE THREAD

**Issue by Dnu12** [PhilipHazel/pcre2#97]
Hi !

     I cloned this repo and tried to install it using auto tools( configure; make;make install ) but I couldn't find the configure script in the repo . So I tried to run 'autoconf' ,it did generate configure script but I got error messages .am I missing something ?

 
<img width="617" alt="Screenshot 2022-04-08 at 12 08 11 PM" src="https://user-images.githubusercontent.com/28951334/162379095-464966ef-8169-47f8-b82e-73ca3ee407de.png">

**Comment by zherczeg** [comment]
Use `./autogen.sh`

**Comment by Dnu12** [comment]
But in README file ,it was mentioned to run 'configure' script ( in section 'building PCRE2 using auto tools' ).I could not find anything about 'autogen.sh' in README file. Is it generally followed to run autogen.sh ? Sorry of being ignorant but at least it could be mentioned in the docs .(I'm happy to make the change.)

**Comment by Dnu12** [comment]
@ltrzesniewski Thanks ! I have the configure file when I use a release .

**Comment by PhilipHazel** [comment]
I have updated the README file to state that ./autogen.sh must be run if the files are downloaded from Git.
